### ISSUE TITLE
custom image - Failed to load settings from /opt/bitnami/elasticsearch/config/elasticsearch.yml]; nested: AccessDeniedException

### ISSUE THREAD

**Issue by loadednet** [bitnami/bitnami-docker-elasticsearch#102]
### Name and Version

bitnami/bitnami-docker-elasticsearch7

### What steps will reproduce the bug?

created image as it is described in the readme.
`sudo docker build --build-arg ELASTICSEARCH_PLUGINS=analysis-icu,analysis-phonetic https://github.com/bitnami/bitnami-docker-elasticsearch.git#:7/debian-10 -t magento-elasticsearch`

docker-compose up
Exception in thread "main" SettingsException[Failed to load settings from /opt/bitnami/elasticsearch/config/elasticsearch.yml]; nested: AccessDeniedException[/opt/bitnami/elasticsearch/config/elasticsearch.yml];

docker-compose.yml
the data volumes all have chown -R 1001:1001

```
version: '2'
services:
  elasticsearch-node1:
    image: magento-elasticsearch
    #image: docker.io/bitnami/elasticsearch:7
    #user: root
    environment:
      - ELASTICSEARCH_CLUSTER_NAME=elasticsearch-cluster
      - ELASTICSEARCH_CLUSTER_HOSTS=elasticsearch-node1,elasticsearch-node2,elasticsearch-node3
      - ELASTICSEARCH_NODE_NAME=elasticsearch-node1
      - ELASTICSEARCH_HEAP_SIZE=1g
      - ES_JAVA_OPTS=-Xms750m -Xmx750m
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - '/var/www/es7n1:/bitnami/elasticsearch/data'
  
  elasticsearch-node2:
    #image: docker.io/bitnami/elasticsearch:7
    image: magento-elasticsearch
    #user: root
    environment:
      - ELASTICSEARCH_CLUSTER_NAME=elasticsearch-cluster
      - ELASTICSEARCH_CLUSTER_HOSTS=elasticsearch-node1,elasticsearch-node2,elasticsearch-node3
      - ELASTICSEARCH_NODE_NAME=elasticsearch-node2
      - ELASTICSEARCH_HEAP_SIZE=1g
      - ES_JAVA_OPTS=-Xms750m -Xmx750m
    volumes:
      - '/var/www/es7n2:/bitnami/elasticsearch/data'

  elasticsearch-node3:
    #image: docker.io/bitnami/elasticsearch:7
    image: magento-elasticsearch
    #user: root
    environment:
      - ELASTICSEARCH_CLUSTER_NAME=elasticsearch-cluster
      - ELASTICSEARCH_CLUSTER_HOSTS=elasticsearch-node1,elasticsearch-node2,elasticsearch-node3
      - ELASTICSEARCH_NODE_NAME=elasticsearch-node3
      - ELASTICSEARCH_HEAP_SIZE=1g
      - ES_JAVA_OPTS=-Xms750m -Xmx750m
    volumes:
      - '/var/www/es7n3:/bitnami/elasticsearch/data'

  kibana:
    image: docker.io/bitnami/kibana:7
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch-node1:9200
      ELASTICSEARCH_HOSTS: '["http://elasticsearch-node1:9200","http://elasticsearch-node2:9200","http://elasticsearch-node3:9200"]'
    volumes:
      - "/var/www/kibana-es7:/bitnami/kibana"
    depends_on:
      - elasticsearch-node1
      - elasticsearch-node2
      - elasticsearch-node3
```

i also tried different approaches that do not work for installing plugns:
e.g: 
on all three nodes and just on node1
environment:
      `- ELASTICSEARCH_PLUGINS=analysis-icu,analysis-phonetic`

on all three nodes:
    `command: ["sh", "-c", "./opt/bitnami/elasticsearch/bin/elasticsearch-plugin install --batch analysis-icu && ./opt/bitnami/elasticsearch/bin/elasticsearch-plugin install --batch analysis-phonetic  && ./opt/bitnami/elasticsearch/bin/elasticsearch"]`
    
 none of them worked...

### What do you see instead?

Exception in thread "main" SettingsException[Failed to load settings from /opt/bitnami/elasticsearch/config/elasticsearch.yml]; nested: AccessDeniedException[/opt/bitnami/elasticsearch/config/elasticsearch.yml];
