### ISSUE TITLE
Error executing 'postInstallation': EEXIST: file already exists, symlink 

### ISSUE THREAD

**Issue by saurabhdhingra89** [bitnami/bitnami-docker-elasticsearch#60]
**Description**

Getting configuration issue when trying to add configs to values.yml. Error:

```
Error executing 'postInstallation': EEXIST: file already exists, symlink '/opt/bitnami/elasticsearch/conf' -> '/opt/bitnami/elasticsearch/config'
```

Above issue is on elastic:6.3.2 image

**Steps to reproduce the issue:**

1. Add:

```yaml
  config:
    xpack.security.enabled: false
    reindex.remote.whitelist: ["abc.com:9200"]
```

2. Install helm chart
3. Pods are failing with above error

**Describe the results you received:**

**Describe the results you expected:**
Pods should start with above configs
