### ISSUE TITLE
docker-compose-cluster.yml   UnknownHostException

### ISSUE THREAD

**Issue by M1NGc** [bitnami/bitnami-docker-elasticsearch#93]
system: ubuntu
user: root
![image](https://user-images.githubusercontent.com/26264126/120753748-330bfd00-c53e-11eb-9327-fbe7e5531a4f.png)
UnknownHostException: elasticsearch-node3
UnknownHostException: elasticsearch-node2
docker-compose.yml
```yml
version: '2'
services:
  elasticsearch-node1:
    image: docker.io/bitnami/elasticsearch:7
    environment:
      - ELASTICSEARCH_CLUSTER_NAME=elasticsearch-cluster
      - ELASTICSEARCH_CLUSTER_HOSTS=elasticsearch-node1,elasticsearch-node2,elasticsearch-node3
      - ELASTICSEARCH_NODE_NAME=elasticsearch-node1
      - ELASTICSEARCH_HEAP_SIZE=1g
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - 'elasticsearch_node1_data:/bitnami'

  elasticsearch-node2:
    image: docker.io/bitnami/elasticsearch:7
    environment:
      - ELASTICSEARCH_CLUSTER_NAME=elasticsearch-cluster
      - ELASTICSEARCH_CLUSTER_HOSTS=elasticsearch-node1,elasticsearch-node2,elasticsearch-node3
      - ELASTICSEARCH_NODE_NAME=elasticsearch-node2
      - ELASTICSEARCH_HEAP_SIZE=1g
    volumes:
      - 'elasticsearch_node2_data:/bitnami'

  elasticsearch-node3:
    image: docker.io/bitnami/elasticsearch:7
    environment:
      - ELASTICSEARCH_CLUSTER_NAME=elasticsearch-cluster
      - ELASTICSEARCH_CLUSTER_HOSTS=elasticsearch-node1,elasticsearch-node2,elasticsearch-node3
      - ELASTICSEARCH_NODE_NAME=elasticsearch-node3
      - ELASTICSEARCH_HEAP_SIZE=1g
    volumes:
      - 'elasticsearch_node3_data:/bitnami'

  kibana:
    image:  docker.io/bitnami/kibana:7
    container_name: kibana
    environment:
      - SERVER_NAME=kibana
      - ELASTICSEARCH_URL=http://elasticsearch-node1:9200
      - XPACK_MONITORING_ENABLED=true
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch-node1

volumes:
  elasticsearch_node1_data:
    driver: local
  elasticsearch_node2_data:
    driver: local
  elasticsearch_node3_data:
    driver: local
```
