### ISSUE TITLE
Env ELASTICSEARCH_DISABLE_GC_LOGS not working as intended

### ISSUE THREAD

**Issue by melck** [bitnami/bitnami-docker-elasticsearch#97]
### Name and Version

bitnami/elasticsearch:7.16.2

### What steps will reproduce the bug?

1. Example of docker-compose :
```yaml
version: '3.7'
volumes:
  elasticsearch:
services:
  elasticsearch:
    image: bitnami/elasticsearch:7.16.2
    volumes:
      - elasticsearch:/bitnami/elasticsearch/data
    environment:
      ELASTICSEARCH_CLUSTER_NAME: test-cluster
      ELASTICSEARCH_HEAP_SIZE: 512m
      ELASTICSEARCH_LOCK_ALL_MEMORY: 'true'
      ELASTICSEARCH_DISABLE_GC_LOGS: 'yes'
```
2. Start elasticsearch container
3. Check logs with `docker-compose exec elasticsearch ls -lh /opt/bitnami/elasticsearch/logs`

### What is the expected behavior?

This folder should be empty of logs.

### What do you see instead?

```
❯ docker-compose exec elasticsearch ls -lh /opt/bitnami/elasticsearch/logs
total 568K
-rw-r--r-- 1 1001 root 358K Apr  5 09:31 gc.log
-rw-r--r-- 1 1001 root 1.8K Apr  5 09:23 gc.log.00
-rw-r--r-- 1 1001 root  61K Apr  5 09:23 gc.log.01
-rw-r--r-- 1 1001 root 1.8K Apr  5 09:23 gc.log.02
-rw-r--r-- 1 1001 root  61K Apr  5 09:23 gc.log.03
-rw-r--r-- 1 1001 root 1.8K Apr  5 09:23 gc.log.04
-rw-r--r-- 1 1001 root  63K Apr  5 09:23 gc.log.05
-rw-r--r-- 1 1001 root 1.8K Apr  5 09:23 gc.log.06
```

### Additional information

When commenting following line in `/opt/bitnami/elasticsearch/config/jvm.options`, it disable gc log correctly :
```
9-:-Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m
```
